apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipprocessing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipprocessing-api
  template:
    metadata:
      labels:
        app: zipprocessing-api
    spec:
      containers:
        - name: zipprocessing-api
          image: zipprocessing-api:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: zipprocessing-api-service
spec:
  type: LoadBalancer
  selector:
    app: zipprocessing-api
  ports:
    - port: 5000
      targetPort: 5000
